# docker-compose.yml
version: "3.9"
services:
  web:
    build: .
    command: gunicorn notes_project.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
      - static_volume:/app/staticfiles  # Том для статических файлов
    ports:
      - "8000:8000"
    environment:
      DEBUG: "0"  # В продакшене выключаем DEBUG

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles  # Том для статических файлов
    ports:
      - "80:80"
    depends_on:
      - web

volumes:
  static_volume:  # Определение тома для статических файлов
